// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/school-app/Calendar.tsx": () => import("../components/mockups/school-app/Calendar.tsx"),
  "./components/mockups/school-app/Classes.tsx": () => import("../components/mockups/school-app/Classes.tsx"),
  "./components/mockups/school-app/Dashboard.tsx": () => import("../components/mockups/school-app/Dashboard.tsx"),
  "./components/mockups/school-app/Grades.tsx": () => import("../components/mockups/school-app/Grades.tsx"),
  "./components/mockups/school-app/Students.tsx": () => import("../components/mockups/school-app/Students.tsx"),
  "./components/mockups/school-app/Teachers.tsx": () => import("../components/mockups/school-app/Teachers.tsx")
};
